//
// City.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct City: Codable { 


    public var id: Int64
    public var name: String
    public var image: String?
    public var rating: Double?

    public init(id: Int64, name: String, image: String?, rating: Double?) {
        self.id = id
        self.name = name
        self.image = image
        self.rating = rating
    }

}
